language: node_js

node_js:
  - "10.16.1"

cache:
  directories:
    - node_modules

script:
  - npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

